// decentralized-quiz-react/src/App.js
import './App.css';
import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import NavigationBar from './components/NavigationBar';
import QuestionForm from './components/QuestionForm';

function App() {
  return (
      <div className="App">
        <NavigationBar />
        <div className="container">
          <h1>Question Submission</h1>
          <QuestionForm />
        </div>
      </div>
  );
}

export default App;

// decentralized-quiz-vuejs/src/App.vue
<template>
  <div id="app">
    <NavigationBar />
    <div class="container">
      <h1>Question Submission</h1>
      <QuestionForm />
    </div>
  </div>
</template>

<script>
import NavigationBar from './components/NavigationBar.vue'
import QuestionForm from './components/QuestionForm.vue'

export default {
  name: 'App',
  components: {
    NavigationBar,
    QuestionForm
  }
}
</script>

<style>
@import './assets/app.css';
</style>
