// decentralized-quiz-react/src/components/NavigationBar.js
import React from 'react';
import { Navbar, Nav } from 'react-bootstrap';

const NavigationBar = () => {
    return (
        <Navbar bg="light" expand="lg">
            <Navbar.Brand href="#">Decentralized Quiz</Navbar.Brand>
            <Navbar.Toggle aria-controls="basic-navbar-nav" />
            <Navbar.Collapse id="basic-navbar-nav">
                <Nav className="mr-auto">
                    <Nav.Link href="question-submission.html">Submit Question</Nav.Link>
                    <Nav.Link href="quiz-taking.html">Take Quiz</Nav.Link>
                    <Nav.Link href="answer-checking.html">Check Answers</Nav.Link>
                </Nav>
            </Navbar.Collapse>
        </Navbar>
    );
};

export default NavigationBar;

// decentralized-quiz-vuejs/src/components/NavigationBar.vue
<template>
  <b-navbar toggleable="lg" type="light" variant="light">
    <b-navbar-brand href="#">Decentralized Quiz</b-navbar-brand>

    <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>

    <b-collapse id="nav-collapse" is-nav>
      <b-navbar-nav>
        <b-nav-item href="question-submission.html">Submit Question</b-nav-item>
        <b-nav-item href="quiz-taking.html">Take Quiz</b-nav-item>
        <b-nav-item href="answer-checking.html">Check Answers</b-nav-item>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>

<script>
export default {
  name: 'NavigationBar'
}
</script>
